include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/python.yml'

stages:
  - test
  - build
  - publish

unit test and feature test:
  stage: test
  image: python:3.9
  script:
    - pip install --no-cache-dir -r requirements/test.txt
    - DATABASE_PATH=security-txt-policy-server.json pytest -vvv --cov-branch --cov=security_txt_policy_server --cov-config=.coveragerc --cov-fail-under=95 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
